# Ejemplo 3.8

Nota: a este documento lo podremos ejecutar de manera dinámica si tienen instalado:

- Python 3.5 o más nuevo instalado.
- [Jupyter Notebook](https://jupyter.readthedocs.io/en/latest/install.html).


Ejecutar este documento en forma dinámica: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rirastorza/ejemplosODE/blob/master/Sistemas_no_lineales/ejemplo3_8.ipynb)

La visualización del mismo es óptima utilizando Jupyter Notebook.

### Referencias

- Naón, C. M., Rossignoli, R., & Santángelo, E. M. (2014). Ecuaciones diferenciales en Física. Editorial de la Universidad Nacional de La Plata (EDULP).

- Edwards, C. H., & Penney, D. E. (2008). Elementary differential equations. Pearson Higher. Edición 6.


In [1]:

"""
Ejemplo 3.8, producto de matrices, calculo del rango, etc.

@author: Ramiro Irastorza
"""


import numpy as np


#Cálculo del determinante de una matriz
A = np.array([[-2., 17., 4.], [-1.0, 6.0, 1.0], [0.0, 1.0, 2.0]])

lam1 = np.linalg.eig(A)

print('autovalores:', lam1)

print('Rango:',np.linalg.matrix_rank(A))
print('Rango:',np.linalg.matrix_rank(A-2*np.eye(3,3)))

print('(A-lambdaI)^2:',np.linalg.matrix_power(A-2*np.eye(3,3),2))
print('(A-lambdaI)^3:',np.linalg.matrix_power(A-2*np.eye(3,3),3))


autovalores: (array([2.00001275+0.00000000e+00j, 1.99999362+1.10421695e-05j,
       1.99999362-1.10421695e-05j]), array([[-7.07124812e-01+0.00000000e+00j,  7.07097765e-01+3.12324696e-05j,
         7.07097765e-01-3.12324696e-05j],
       [-9.01543079e-06+0.00000000e+00j, -4.50788782e-06+7.80809251e-06j,
        -4.50788782e-06-7.80809251e-06j],
       [-7.07088750e-01+0.00000000e+00j,  7.07115797e-01+0.00000000e+00j,
         7.07115797e-01-0.00000000e+00j]]))
Rango: 3
Rango: 2
(A-lambdaI)^2: [[-1.  4.  1.]
 [ 0.  0.  0.]
 [-1.  4.  1.]]
(A-lambdaI)^3: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
