# Ejemplo adicional 2.7

Nota: a este documento lo podremos ejecutar de manera dinámica si tienen instalado:

- Python 3.5 o más nuevo instalado.
- [Jupyter Notebook](https://jupyter.readthedocs.io/en/latest/install.html).


Ejecutar este documento en forma dinámica: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rirastorza/ejemplosODE/blob/master/Sistemas_lineales/ejemplo_adicional_2_7.ipynb)

La visualización del mismo es óptima utilizando Jupyter Notebook.

### Referencias

- Naón, C. M., Rossignoli, R., & Santángelo, E. M. (2014). Ecuaciones diferenciales en Física. Editorial de la Universidad Nacional de La Plata (EDULP).

- Edwards, C. H., & Penney, D. E. (2008). Elementary differential equations. Pearson Higher. Edición 6.


In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Created on Sat Sep 03 10:13:41 2016

Matrices y sistemas lineales
(varios ejemplos)

@author: Ramiro Irastorza
"""

import numpy as np


#Cálculo del determinante de una matriz
A = np.array([[3.0, 1.0, -2.0], [4.0, 2.0, 1.0], [-2.0, 3.0, 5.0]])
print('La matriz A=',A)
detA = np.linalg.det(A)
print('El determinante es:',detA)
print('-------------------------')


#Cálculo del determinante de una matriz
A = np.array([[1.0, 3.0, 1.0, -1.0], [2.0, 1.0, 0.0, 1.0], [0.0, -2.0, 2.0, 1.0], [5.0, 4.0, 1.0, 0.0]])
print('La matriz A=',A)
detA = np.linalg.det(A)
print('El determinante es:',detA)
print('-------------------------')

#Inversa de una matriz
B = np.array([[1.0, 3.0], [2.0, 1.0]])
invB = np.linalg.inv(B)
print('La matriz B=',B)
print('La inversa de B es=',invB)
print('-------------------------')

#Autovalores y autovectores
C = np.array([[0.0, 0.0, 0.0], [1.0, 0.0, 2.0], [0.0, 1.0, 1.0]])
#Autovalores
w,v = np.linalg.eig(C)
print('La matriz C=',C)
print('Autovalores:', w)
print('Autovectores:', v)

#Autovalores y autovectores
D = np.array([[1.0, 2.0], [2.0, 1.0]])
#Autovalores
w,v = np.linalg.eig(D)
print('La matriz C=',D)
print('Autovales:', w)
print('Autovectores:', v)
print('-------------------------')


La matriz A= [[ 3.  1. -2.]
 [ 4.  2.  1.]
 [-2.  3.  5.]]
El determinante es: -33.0
-------------------------
La matriz A= [[ 1.  3.  1. -1.]
 [ 2.  1.  0.  1.]
 [ 0. -2.  2.  1.]
 [ 5.  4.  1.  0.]]
El determinante es: 22.000000000000004
-------------------------
La matriz B= [[1. 3.]
 [2. 1.]]
La inversa de B es= [[-0.2  0.6]
 [ 0.4 -0.2]]
-------------------------
La matriz C= [[0. 0. 0.]
 [1. 0. 2.]
 [0. 1. 1.]]
Autovalores: [ 2. -1.  0.]
Autovectores: [[ 0.          0.          0.81649658]
 [ 0.70710678  0.89442719  0.40824829]
 [ 0.70710678 -0.4472136  -0.40824829]]
La matriz C= [[1. 2.]
 [2. 1.]]
Autovales: [ 3. -1.]
Autovectores: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
-------------------------
